<?php
/**
 * Mageplaza
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Mageplaza.com license that is
 * available through the world-wide-web at this URL:
 * https://www.mageplaza.com/LICENSE.txt
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterCoupon
 * @copyright   Copyright (c) 2018 Mageplaza (https://www.mageplaza.com/)
 * @license     https://www.mageplaza.com/LICENSE.txt
 */

namespace Mageplaza\Webhook\Block\Adminhtml\Hook\Edit\Tab\Renderer;

use Magento\Backend\Block\Template\Context;
use Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray;
use Magento\Framework\Data\Form\Element\AbstractElement;
/**
 * Class LinkGenerator
 * @package Mageplaza\BetterCoupon\Block\Adminhtml\System\Config
 */
class Headers extends AbstractFieldArray
{
    protected $_template = 'Mageplaza_Webhook::hook/headers.phtml';
    protected $_element;

    /**
     * Header constructor.
     * @param Context $context
     * @param array $data
     */
    public function __construct(Context $context, array $data = [])
    {
        parent::__construct($context, $data);
    }

    /**
     * Initialise form fields
     *
     * @return void
     */
    public function _construct()
    {
        $this->addColumn('name', ['label' => __('Name')]);
        $this->addColumn('value', ['label' => __('Value')]);

        $this->_addAfter = false;

        parent::_construct();
    }

    /**
     * Get Button Label
     *
     * @return \Magento\Framework\Phrase
     */
    public function getAddButtonLabel()
    {
        return __('Add');
    }

//    public function _getElementHtml(\Magento\Framework\Data\Form\Element\AbstractElement $element)
//    {
//        return parent::_getElementHtml($element); // TODO: Change the autogenerated stub
//    }
//    public function getElement()
//    {
//        return $this->_element;
//    }
//    public function render(AbstractElement $element)
//    {
//        $this->_element = $element;
//        return parent:: render($element);
//    }
}
